### ISSUE TITLE
First Gallery 적용방법 문의

### ISSUE THREAD

**Issue by 76charles** [dev-goose/app-first-gallery#1]
바쁘신데 귀찮게해서 죄송합니다. ^^;;

PC에 APM 설치해서 로컬로 아래와 같이 적용하였습니다.
![image](https://cloud.githubusercontent.com/assets/16873641/12635335/850b7fe6-c5c5-11e5-9ebe-1c7e22bfc976.png)

[JSON]
![image](https://cloud.githubusercontent.com/assets/16873641/12635235/7a50f96a-c5c4-11e5-88c7-489e98abb739.png)

[Nest]
![image](https://cloud.githubusercontent.com/assets/16873641/12635245/8f9e0c04-c5c4-11e5-8c44-4d4be13ef9b9.png)

[Navigation]
![image](https://cloud.githubusercontent.com/assets/16873641/12635256/afcbfa40-c5c4-11e5-9e0b-169d4bcf05f8.png)

[Intro]
![image](https://cloud.githubusercontent.com/assets/16873641/12635267/c348f65e-c5c4-11e5-966e-feb2902f34b8.png)

**해당결과가 아래와 같이 나오는데... 어디를 손봐줘야 하나요?**
![image](https://cloud.githubusercontent.com/assets/16873641/12635318/543eb4f0-c5c5-11e5-9a6b-6ee37088ea17.png)
![image](https://cloud.githubusercontent.com/assets/16873641/12635325/64399dfc-c5c5-11e5-839e-9ee277bf1d06.png)
![image](https://cloud.githubusercontent.com/assets/16873641/12635329/7256d8a0-c5c5-11e5-8c9a-0486abf0f524.png)

**Comment by RedgooseDev** [comment]
환경설정 json에서 확인해봐야할 부분이 있겠네요.

#### 첫화면에서 글이 안나오는 현상
```
{
    srl : {
        "app" : 2
    }
}
```
이 부분이 app srl번호를 바꿔주면 될겁니다.  
둥지 목록에서 app 목록 (스크린샷을 보니 품질경영시스팀이겠네요.)을 선택해보면 url에서 숫자 부분이 붙는걸 확인할 수 있을겁니다. 처음 APP 모듈에서 만들었으면 1일 겁니다.


#### 둥지 글이 출력 안되는 현상

메뉴가 자동으로 만들어지는게 아니며 네비게이션 json 값을 직접 고쳐주시면 됩니다. json 모듈에 등록했으니 링크를 고쳐주시면 되겠죠.  
https://github.com/dev-goose/app-first-gallery/wiki/3.-Settings#link-guide
이 부분인 링크 가이드를 주소를 수정하는 규칙을 적어뒀으니 참고해주세요.


#### 본문글이 깨져나오는 현상

다음 json 부분을 볼 수 있습니다. 본문글에 대한 설정인데 에디터를 사용한다면 markdown을 html로 바꿔주시면 될겁니다.
```
{
    "article": {
         "type": "markdown",
         "updateHit": true,
         "updateLike": true,
         "cookiePrefix": "goose-"
    }
}
```

https://github.com/dev-goose/app-first-gallery/wiki/3.-Settings#article
자세한 내용은 링크를 참고해주세요.

**Comment by 76charles** [comment]
감사합니다. 
마지막에 본문글에 그림이 안나오는 것만 안되고 나머지는 해결되었습니다.
타입을 html로 바꿔바도 그대로네요.. Nest에서 아티클 스킨을 이것저것 바까바도 안되구요..
첫 화면에 나오는 그림을 클릭해도 그림이 안나옵니다. ㅠ.ㅠ

이상한거는 제일 처음에 그림파일 하나 올린건 또 나오네요.. ㅡ,.ㅡ;;;

![image](https://cloud.githubusercontent.com/assets/16873641/12638104/cb14908c-c5dd-11e5-9743-42e1aa2caffd.png)

![image](https://cloud.githubusercontent.com/assets/16873641/12638122/f0fbe4d0-c5dd-11e5-8cd2-9400bfd8c774.png)

**Comment by RedgooseDev** [comment]
![cap 2016-01-28 16-45-41-423](https://cloud.githubusercontent.com/assets/1978100/12638193/9ca980f8-c5de-11e5-8a2d-3c7d3b59cf1d.png)

사진을 올릴때 사진 업로드 창에서 이런 아이콘을 보셨을거예요. 3번째 아이콘이 본문삽입 아이콘인데 그걸 눌러주면 본문에 사진이 올라갑니다. 이렇게 번거롭게 따로 버튼을 눌러서 본문에 넣어주는 이유는 자유로운 편집을 하기위하여 그런겁니다.

에디터라면 본문에 올라간 이미지가 보이겠지만, markdown이라면 이미지 주소 코드로 올라갈거예요 ㅎㅎ

**Comment by 76charles** [comment]
아... 막 위에글 수정하고 있었는데요.. ㅎㅎㅎ

본문삽입 누르니 잘 되더군요!!

좋은 프로그램 만들어 주셔서 감사합니다!!

**Comment by RedgooseDev** [comment]
하하~ 잘 되어서 다행이네요.. 설치하는데 과정이 어려웠겠지만 삽질을 하면서 많이 이해했을거라 생각되네요.  
이렇게 사용한다는것을 보니 만든 보람이 생기네요.

감사합니다~

**Comment by RedgooseDev** [comment]
참고로 first-gallery 팁을 알려드리자면 본문글에서 키보드 왼쪽 방향 누르면 이전글로 넘어가고 오른쪽 누르면 다음글로 가고 esc 키 누르면 닫히면서 목록으로 가요 ㅎㅎㅎㅎ

**Comment by 76charles** [comment]
대박~ 좋네요 ㅎㅎ
적용법 or 사용법이 쉽지는 않지만 말씀하신것처럼 삽질하면서 조금 이해가 되서 어느 정도는 알것네요 ㅎㅎㅎ 그래도 아직 갈길이 머네요... 
원하는게 첫 페이지에 로그인화면 만들어서 품질팀만 들어오게 하고 들어가서는 
첫 페이지에 스케쥴표? 해야할일 나오게 하고.. 메뉴 같은거로는 제품 불량사진들 있는 사이트나 Nest, 회사 매뉴얼들 다운 받을수 있거나 매뉴얼을 그대로 올려놓거나... 이런식으로 하나하나 늘려갈 생각이거든요.. ㅎㅎㅎ

**Comment by RedgooseDev** [comment]
goose에서 모듈을 다른 사람들이 개발할 수 있는 환경을 마련해두는걸 최대의 목표로 뒀어요. ㅎㅎ  
팀원들끼리 접근하거나 같이 컨텐츠를 올려서 데이터를 쌓을 수 있는걸 기대하고 있어요 :)

물론 별도의 모듈을 개발하면서 db table 추가 가능하고 {GOOSE}/module/index/ 경로에서 테이블 설치할 수 있습니다. 물론 모듈 개발에서 거기에 있는 몇가지 규칙만 지켜진다면 개발에 한계가 없다고 봅니다. 개인적으로 필요하다면 커뮤니티나 쇼핑몰 같은 프로그램도 제작 가능하다고 생각하고 있어요 ㅎㅎ  
제가 몸이 하나뿐이라서 엄두가 안나서요;;

http://redgoosedev.github.io/goose/#Documentation/DocDevelopModule  
여기에 모듈 개발에 대해서 최대한 적었지만 부족할거예요.

동영상 강좌를 만들거나 좀 벌려보고 싶지만 일단 컨텐츠를 만들어서 공개하는게 우선인거라 생각이 되어서 조용히 도구들이나 만들고 있네요 ㅎㅎ;;

활용만 잘하면 가능성은 끝없다고 생각됩니다. 헤헷~

많이 분석해주세요~ 모르는건 최대한 알려드리겠습니다. :)

**Comment by RedgooseDev** [comment]
둥지에서 권한 설정에 대해서 작업이 빠져있는데 조만간 특정 둥지에 대해서 접근 권한 설정을 좀 손봐야겠네요. 골치아퍼.... ㅠㅠ

**Comment by 76charles** [comment]
넵~ 알겠습니다. ㅎㅎ 막히면 문의드리러 올깨요..

접근 권한설정은 메인에 있는 글 읽어봐서 알구 있어서요.. 
제가 자바스크립트는 몰라도 PHP는 조금 할줄알아서요.. 말 그대로 조금.. (그누보드 스킨 만들정도?)
그래서 그냥 다이렉트로 로그인 체크를 디비에서 직접 비교하려고 했지요 ㅎㅎㅎ
사용자는 관리자로 접속해서 유저에서 생성해주면 되니까요 ㅋㅋ

나머지 부분들도 솔직히 모듈만들어서 하지는 못하고 모듈이 없는것은 PHP, HTML, CSS 써서 
직접 코딩하려고 하고 있습니다... 한두달 잡고하는거 아니고 그냥 시간날때 짬짬이 할 거라서
자바스크립트도 책 하나 사서 공부 좀 해보려고 합니다. ㅎㅎㅎㅎ

도구들 만드시면 또 열심히 사용해 보겠습니다. ㅎㅎ

날 추운데 건강하십쇼~~~!!

**Comment by RedgooseDev** [comment]
js야.. 필수는 아녜요 ㅎㅎㅎ
php, html, css 만 볶아도 충분히 뭐든지 할 수 있으니깐요. js를 하면 좀더 편한것들이 있으니깐요. ㅎㅎ 비동기화, UI 부분들이 있겠죠 :)

화이팅하시구요~ 좋은하루돠세요~
